package faq

var BalanceSheetFaq = []string{
	"What is the company’s overall financial health based on its balance sheet?",
	"How does the company’s debt compare to its equity, and does it look risky?",
	"What percentage of the company’s assets are funded by debt versus its own money?",
	"Has the company’s value (assets or liabilities) changed a lot over time?",
	"Does the company have enough cash to cover its short-term bills?",
	"How well is the company using its assets to generate profits?",
	"How does the company’s profitability compare to its competitors?",
	"Has the company’s retained earnings (profits kept in the business) been growing or declining?",
	"Has the company’s inventory changed a lot? Does that tell us something about how well it’s managing operations?",
	"How well is the company turning its assets into sales or revenue?",
	"Does the company have enough working capital (short-term funds) for daily operations?",
	"Has the company’s cash situation improved or worsened recently? What does that mean for the business?",
	"Is the company in danger of running out of cash?",
	"How much of the company’s debt is due soon, and how much can be paid off later?",
	"Has the company’s payables (money it owes to others) increased significantly?",
	"Is the company’s book value (what it owns minus what it owes) increasing or decreasing over time?",
	"Has the company been adding more intangible assets (like goodwill), and does that suggest overvaluation?",
	"Has the company been investing more in long-term assets like capital leases or investments?",
	"How does the company’s book value per share compare to its current stock price?",
	"Is the company’s debt level too high compared to its equity, and does this affect its valuation risk?",
	"How much is the company’s worth after subtracting its debts (net asset value)?",
	"Does the company’s book value (what it owns minus what it owes) align with its market value or stock price?",
	"What is the company’s overall value (enterprise value) when we include its market value and debt?",
	"Is the company’s book value per share higher or lower than its stock price?",
	"How does the company’s stock price compare to its book value per share (price-to-book ratio)?",
	"Does the company’s debt level impact its stock price or valuation risk?",
	"Is the company generating enough free cash flow (extra cash after expenses) to create value for shareholders?",
	"How does the company’s goodwill affect its book value, and does it risk overvaluation or needing to be written down?",
	"Based on the company’s book value and market price, is it underpriced or overpriced in the market?",
	"How does the company’s debt compared to equity affect its overall value and risk of over-leveraging?",
}
