package faq

var EtfFaq = []string{
	"Which are the different ETF asset classes and what is the difference between them?",
	"What are the main factors that influence ETF performance over time?",
	"What trends have emerged in ETF investment strategies in recent years?",
	"Which ETFs have the most assets under management?",
	"How has the total assets under management (AUM) in ETFs changed over time?",
	"What are the key advantages of investing in ETFs?",
	"How do ETFs provide diversification benefits to investors?",
	"What are the risks associated with ETFs compared to other investment vehicles?",
	"What are the most common types of ETFs available in the market?",
	"How do market conditions impact ETFs differently than other assets?",
	"What role do ETFs play in passive versus active investing?",
	"How do sector-specific ETFs perform compared to broad-market ETFs?",
	"What impact do macroeconomic events have on ETF performance?",
	"How do ETFs generate income for investors (e.g., dividends, interest)?",
	"How do ETFs fit into a long-term investment strategy?",
	"How do ETFs make money for investors?",
	"Are ETFs good for beginners?",
	"How do I choose the right ETF to invest in?",
	"What is the difference between stock ETFs and bond ETFs?",
	"Can I lose money investing in ETFs?",
	"How do ETFs track an index?",
	"Do ETFs pay dividends?",
	"How much money do I need to start investing in ETFs?",
	"Are ETFs safer than individual stocks?",
	"Can I invest in ETFs for the long term?",
	"How do I buy and sell ETFs?",
	"What is the difference between an ETF and a mutual fund?",
	"Do I need a brokerage account to invest in ETFs?",
	"How often do ETF prices change?",
	"What happens if an ETF shuts down?",
	"Are there fees when buying or selling ETFs?",
	"Can I invest in ETFs with small amounts of money?",
	"How do international ETFs work?",
	"What is the difference between an actively managed ETF and a passive ETF?",
	"Can I build a retirement portfolio using ETFs?",
}
