package faq

var StockOverviewFaq = []string{
	"What does the company profile tell me about a stock?",
	"How can I use the sector and industry information to evaluate a stock?",
	"Why is the IPO date important when analyzing a stock?",
	"How does the CEO’s leadership impact a company’s stock performance?",
	"What is EPS (Earnings Per Share), and why does it matter?",
	"How can I interpret EPS growth when analyzing a stock?",
	"What does revenue growth indicate about a company’s future potential?",
	"How accurate are stock price target estimates, and should I rely on them?",
	"What does the P/E (Price-to-Earnings) ratio tell me about a stock?",
	"How do I use the P/B (Price-to-Book) ratio to determine if a stock is undervalued?",
	"What is the difference between market cap and enterprise value (EV)?",
	"How does the debt-to-equity ratio impact a company’s financial health?",
	"What is the significance of the dividend yield, and how does it affect investors?",
	"How can I identify financially stable stocks using ratios?",
	"What does return on equity (ROE) tell me about a company’s profitability?",
	"Why is the quick ratio important for assessing a company's short-term liquidity?",
	"What is earnings yield, and how does it compare to dividend yield?",
	"How do I compare stocks in the same sector to pick the best investment?",
	"What are some good indicators to look at before buying or selling a stock?",
	"How often should I review financial ratios to track a stock’s performance?",
	"What is the EV/EBITDA ratio, and how does it compare to the P/E ratio?",
	"How does the Price-to-Sales (P/S) ratio help evaluate a stock?",
	"What does the Price-to-Free-Cash-Flow (P/FCF) ratio indicate about a company?",
	"Why is the Debt/EBITDA ratio important for understanding a company’s leverage?",
	"How do asset turnover and inventory turnover ratios impact a company's efficiency?",
	"What does the current ratio tell me about a company's ability to pay short-term liabilities?",
	"How can I use the Return on Assets (ROA) ratio to measure a company’s profitability?",
	"What is the significance of the Return on Invested Capital (ROIC) ratio?",
	"How do earnings yield and dividend yield differ in evaluating stocks?",
	"What does the payout ratio tell me about a company's dividend sustainability?",
	"Can you give me a high-level overview of this stock?",
	"Can you do a quick valuation of the stock?",
	"What are the key financial ratios for this stock, and what do they indicate?",
	"What is the current P/E ratio of this stock, and what does it tell me?",
	"How has this stock’s revenue and earnings grown over the last few years?",
	"What are analysts' price targets for this stock, and how reliable are they?",
	"What is this stock’s dividend yield, and how sustainable are its payouts?",
	"How has this stock performed during past economic downturns?",
	"What are the biggest risks associated with investing in this stock?",
	"What are the key factors driving this stock’s future growth potential?",
}
